baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pre = 'house'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pre = 'newspaper'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pre = 'tag'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
# Override custom CSS with default PageFind search styles
enablePagefindCSS = true 

[params.navigationBar]
# Show both icons and text
iconsHaveLabels = true
# Seperate the first icon with a line break
seperatorForFirstIcon = true

[params.smallTiles]
# Type of content to appear in small tiles
type = "categories"  # "categories" or "tags"

[params.bigTiles]
# Number of tiles to show
count = 3
# Max characters for excerpt.
truncate = 150

